/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenovo
 */
public class Pos extends javax.swing.JFrame {

    /**
     * Creates new form Pos
     */
    public Pos() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/logo_casa_blanca_peque.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public void costoProducto() {
        double suma = 0;
        for (int i = 0; i < tblProducto.getRowCount(); i++) {
            suma = suma + Double.parseDouble(tblProducto.getValueAt(i, 2).toString());
        }
        txtSubTotal.setText(Double.toString(suma));
        double total1 = Double.parseDouble(txtSubTotal.getText());
        double iva = (total1 * 19) / 100;

        String ivaTotal = String.format("$ %.2f", iva);
        txtIva.setText(ivaTotal);

        String total = String.format("$ %.2f", total1 + iva);
        txtTotal.setText(total);

        String codigoBarra = String.format("Total: %.2f", iva, total1);
        txtTotal.setText(total);
    }

    public void cambio() {
        double suma = 0, iva = 19;
        double cambio = Double.parseDouble(txtRecibido.getText());
        for (int i = 0; i < tblProducto.getRowCount(); i++) {
            suma = suma + Double.parseDouble(tblProducto.getValueAt(i, 2).toString());
        }
        double cIva = (suma * iva) / 100;
        double cCambio = cambio - (suma + cIva);
        String vueltas = String.format("Total: %.2f", cCambio);
        txtCambio.setText(vueltas);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnMexicana = new javax.swing.JButton();
        btnPastor = new javax.swing.JButton();
        btnCarbonara = new javax.swing.JButton();
        btnExplosionTocineta = new javax.swing.JButton();
        btnCasaBlanca = new javax.swing.JButton();
        btnPeperoni = new javax.swing.JButton();
        btnTentacionEspañola = new javax.swing.JButton();
        btnRanchera = new javax.swing.JButton();
        btnBarbacoa = new javax.swing.JButton();
        btnCuatroEstaciones = new javax.swing.JButton();
        btnCarnes = new javax.swing.JButton();
        btnDiavola = new javax.swing.JButton();
        btnPolloBbq = new javax.swing.JButton();
        btnMilo = new javax.swing.JButton();
        btnPolloChampiñones = new javax.swing.JButton();
        btnLimonadaCoco = new javax.swing.JButton();
        btnPolloMiel = new javax.swing.JButton();
        btnCocaCola = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnUno = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        btnCuatro = new javax.swing.JButton();
        btnSiete = new javax.swing.JButton();
        btnCero = new javax.swing.JButton();
        btnDos = new javax.swing.JButton();
        btnTres = new javax.swing.JButton();
        btnCinco = new javax.swing.JButton();
        btnSeis = new javax.swing.JButton();
        btnOcho = new javax.swing.JButton();
        btnNueve = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnBorrarTodo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducto = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIva = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtRecibido = new javax.swing.JTextField();
        txtCambio = new javax.swing.JTextField();
        cbxMetodoPago = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        btnPago = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnMail = new javax.swing.JButton();
        txtCodigoBarra = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CASA BLANCA PIZZERIA");
        setPreferredSize(new java.awt.Dimension(1350, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_casa_blanca_peque.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel2.setText("CASA BLANCA ");

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N
        jLabel3.setText("Pizzeria-heladeria ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(507, 507, 507)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(581, 581, 581)
                        .addComponent(jLabel3)))
                .addContainerGap(525, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 90));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnMexicana.setFont(new java.awt.Font("Monotype Corsiva", 1, 10)); // NOI18N
        btnMexicana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pizza_Mexicana_120_60.png"))); // NOI18N
        btnMexicana.setText("Pizza mexicana");
        btnMexicana.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMexicana.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMexicana.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMexicana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMexicanaActionPerformed(evt);
            }
        });

        btnPastor.setFont(new java.awt.Font("Monotype Corsiva", 1, 10)); // NOI18N
        btnPastor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pizza_pastor.png"))); // NOI18N
        btnPastor.setText("Pizza al pastor");
        btnPastor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPastor.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnPastor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPastor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastorActionPerformed(evt);
            }
        });

        btnCarbonara.setFont(new java.awt.Font("Monotype Corsiva", 1, 10)); // NOI18N
        btnCarbonara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pizza_carbonara.jpg"))); // NOI18N
        btnCarbonara.setText("Pizza carbonara");
        btnCarbonara.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCarbonara.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCarbonara.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCarbonara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarbonaraActionPerformed(evt);
            }
        });

        btnExplosionTocineta.setFont(new java.awt.Font("Monotype Corsiva", 1, 10)); // NOI18N
        btnExplosionTocineta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pizza_tocineta.jpg"))); // NOI18N
        btnExplosionTocineta.setText("Pizza explosion de tocineta");
        btnExplosionTocineta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExplosionTocineta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnExplosionTocineta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExplosionTocineta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExplosionTocinetaActionPerformed(evt);
            }
        });

        btnCasaBlanca.setFont(new java.awt.Font("Monotype Corsiva", 1, 10)); // NOI18N
        btnCasaBlanca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pizza_casaBlanca.png"))); // NOI18N
        btnCasaBlanca.setText("Pizza casa blanca");
        btnCasaBlanca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCasaBlanca.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCasaBlanca.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCasaBlanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCasaBlancaActionPerformed(evt);
            }
        });

        btnPeperoni.setFont(new java.awt.Font("Monotype Corsiva", 1, 10)); // NOI18N
        btnPeperoni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pizza_peperoni.jpg"))); // NOI18N
        btnPeperoni.setText("Pizza peperoni");
        btnPeperoni.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPeperoni.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnPeperoni.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPeperoni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeperoniActionPerformed(evt);
            }
        });

        btnTentacionEspañola.setFont(new java.awt.Font("Monotype Corsiva", 1, 10)); // NOI18N
        btnTentacionEspañola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pizza_tentacionespanola.jpg"))); // NOI18N
        btnTentacionEspañola.setText("Pizza tentacion española");
        btnTentacionEspañola.setToolTipText("");
        btnTentacionEspañola.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTentacionEspañola.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnTentacionEspañola.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTentacionEspañola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTentacionEspañolaActionPerformed(evt);
            }
        });

        btnRanchera.setFont(new java.awt.Font("Monotype Corsiva", 1, 10)); // NOI18N
        btnRanchera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pizza_ranchera.jpg"))); // NOI18N
        btnRanchera.setText("Pizza ranchera");
        btnRanchera.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRanchera.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRanchera.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRanchera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRancheraActionPerformed(evt);
            }
        });

        btnBarbacoa.setFont(new java.awt.Font("Monotype Corsiva", 1, 10)); // NOI18N
        btnBarbacoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pizza_barbacoa.jpg"))); // NOI18N
        btnBarbacoa.setText("Pizza barbacoa");
        btnBarbacoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBarbacoa.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnBarbacoa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBarbacoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarbacoaActionPerformed(evt);
            }
        });

        btnCuatroEstaciones.setFont(new java.awt.Font("Monotype Corsiva", 1, 10)); // NOI18N
        btnCuatroEstaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pizza_4estaciones.jpg"))); // NOI18N
        btnCuatroEstaciones.setText("Pizza cuatro estaciones");
        btnCuatroEstaciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCuatroEstaciones.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCuatroEstaciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCuatroEstaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuatroEstacionesActionPerformed(evt);
            }
        });

        btnCarnes.setFont(new java.awt.Font("Monotype Corsiva", 1, 10)); // NOI18N
        btnCarnes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pizzas_carnes.jpg"))); // NOI18N
        btnCarnes.setText("Pizza de carnes");
        btnCarnes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCarnes.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCarnes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCarnes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarnesActionPerformed(evt);
            }
        });

        btnDiavola.setFont(new java.awt.Font("Monotype Corsiva", 1, 10)); // NOI18N
        btnDiavola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pizza_diavola.jpg"))); // NOI18N
        btnDiavola.setText("Pizza diavola");
        btnDiavola.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDiavola.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnDiavola.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDiavola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiavolaActionPerformed(evt);
            }
        });

        btnPolloBbq.setFont(new java.awt.Font("Monotype Corsiva", 1, 10)); // NOI18N
        btnPolloBbq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pizza_pollo_BBQ.jpg"))); // NOI18N
        btnPolloBbq.setText("Pizza pollo BBQ");
        btnPolloBbq.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPolloBbq.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnPolloBbq.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPolloBbq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPolloBbqActionPerformed(evt);
            }
        });

        btnMilo.setFont(new java.awt.Font("Monotype Corsiva", 1, 10)); // NOI18N
        btnMilo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/milo frio.jpg"))); // NOI18N
        btnMilo.setText("Milo frio");
        btnMilo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMilo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMilo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiloActionPerformed(evt);
            }
        });

        btnPolloChampiñones.setFont(new java.awt.Font("Monotype Corsiva", 1, 10)); // NOI18N
        btnPolloChampiñones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pizza_pollo_champinones.jpg"))); // NOI18N
        btnPolloChampiñones.setText("Pizza pollo champiñones");
        btnPolloChampiñones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPolloChampiñones.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnPolloChampiñones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPolloChampiñones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPolloChampiñonesActionPerformed(evt);
            }
        });

        btnLimonadaCoco.setFont(new java.awt.Font("Monotype Corsiva", 1, 10)); // NOI18N
        btnLimonadaCoco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limonada coco.jpg"))); // NOI18N
        btnLimonadaCoco.setText("Limonada coco");
        btnLimonadaCoco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimonadaCoco.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnLimonadaCoco.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimonadaCoco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimonadaCocoActionPerformed(evt);
            }
        });

        btnPolloMiel.setFont(new java.awt.Font("Monotype Corsiva", 1, 10)); // NOI18N
        btnPolloMiel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pollo-Miel-Mostaza.jpg"))); // NOI18N
        btnPolloMiel.setText("Pizza pollo miel");
        btnPolloMiel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPolloMiel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnPolloMiel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPolloMiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPolloMielActionPerformed(evt);
            }
        });

        btnCocaCola.setFont(new java.awt.Font("Monotype Corsiva", 1, 10)); // NOI18N
        btnCocaCola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coca cola.jpg"))); // NOI18N
        btnCocaCola.setText("Coca cola 250ml");
        btnCocaCola.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCocaCola.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCocaCola.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCocaCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocaColaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnMexicana, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPastor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarbonara, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExplosionTocineta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCasaBlanca, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPeperoni, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnTentacionEspañola, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRanchera, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBarbacoa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCuatroEstaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarnes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDiavola, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnPolloChampiñones, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPolloBbq, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPolloMiel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCocaCola, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMilo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimonadaCoco, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnCasaBlanca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPeperoni, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExplosionTocineta, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCarbonara, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPastor, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnMexicana, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTentacionEspañola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRanchera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBarbacoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCuatroEstaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCarnes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDiavola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPolloChampiñones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPolloBbq, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPolloMiel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCocaCola, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMilo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimonadaCoco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 590, 270));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnUno.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        btnUno.setText("1");
        btnUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnoActionPerformed(evt);
            }
        });

        jButton22.setText("jButton1");

        jButton23.setText("jButton1");

        jButton25.setText("jButton1");

        jButton26.setText("jButton1");

        btnCuatro.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        btnCuatro.setText("4");
        btnCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuatroActionPerformed(evt);
            }
        });

        btnSiete.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        btnSiete.setText("7");
        btnSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSieteActionPerformed(evt);
            }
        });

        btnCero.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        btnCero.setText("0");
        btnCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCeroActionPerformed(evt);
            }
        });

        btnDos.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        btnDos.setText("2");
        btnDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosActionPerformed(evt);
            }
        });

        btnTres.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        btnTres.setText("3");
        btnTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTresActionPerformed(evt);
            }
        });

        btnCinco.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        btnCinco.setText("5");
        btnCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCincoActionPerformed(evt);
            }
        });

        btnSeis.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        btnSeis.setText("6");
        btnSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeisActionPerformed(evt);
            }
        });

        btnOcho.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        btnOcho.setText("8");
        btnOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOchoActionPerformed(evt);
            }
        });

        btnNueve.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        btnNueve.setText("9");
        btnNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNueveActionPerformed(evt);
            }
        });

        btnPunto.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        btnPunto.setText(".");
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });

        btnBorrarTodo.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        btnBorrarTodo.setText("C");
        btnBorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCero, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBorrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnUno, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTres, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUno, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTres, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCero, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(388, 388, 388)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 190, 270));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        tblProducto.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N
        tblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Producto", "Cantidad", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tblProducto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 260, 240));

        txtArea.setColumns(20);
        txtArea.setRows(5);
        txtArea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane2.setViewportView(txtArea);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 90, 300, 270));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel4.setText("Sub Total");

        txtSubTotal.setEditable(false);
        txtSubTotal.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N
        txtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubTotalActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel5.setText("Iva");

        txtIva.setEditable(false);
        txtIva.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N
        txtIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIvaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel6.setText("Total");

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 330, 170));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel7.setText("Metodo de pago");

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel8.setText("Recibido");

        jLabel9.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel9.setText("Cambio");

        txtRecibido.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N

        txtCambio.setEditable(false);
        txtCambio.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N

        cbxMetodoPago.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N
        cbxMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Efectivo", "Targeta Visa ", "Targeta Master" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCambio))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRecibido))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbxMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtRecibido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 350, 170));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pagar.png"))); // NOI18N
        btnPago.setText("Pago");
        btnPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/imprimir.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/email.png"))); // NOI18N
        btnMail.setText("Mail");
        btnMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMail, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPago)
                    .addComponent(btnLimpiar)
                    .addComponent(btnMail))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnImprimir)
                    .addComponent(btnEliminar))
                .addGap(40, 40, 40))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, 390, 170));

        txtCodigoBarra.setEditable(false);
        txtCodigoBarra.setBackground(new java.awt.Color(204, 204, 204));
        txtCodigoBarra.setFont(new java.awt.Font("C39HrP24DhTt", 0, 24)); // NOI18N
        txtCodigoBarra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoBarra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtCodigoBarra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtCodigoBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoBarraActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodigoBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 330, 260, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubTotalActionPerformed

    private void txtIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIvaActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoActionPerformed
        if (cbxMetodoPago.getSelectedItem().equals("Efectivo")) {
            cambio();
        } else {
            txtCambio.setText("");
            txtRecibido.setText("");
        }
    }//GEN-LAST:event_btnPagoActionPerformed

    private void btnExplosionTocinetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExplosionTocinetaActionPerformed
        double precioProducto = 24000;
        DefaultTableModel model = (DefaultTableModel) tblProducto.getModel();
        model.addRow(new Object[]{"Pizza explosion tocineta", "1", precioProducto});
        costoProducto();
    }//GEN-LAST:event_btnExplosionTocinetaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMailActionPerformed
        EnvioMail envioMail = new EnvioMail();
        envioMail.setVisible(true);
    }//GEN-LAST:event_btnMailActionPerformed

    private void btnMexicanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMexicanaActionPerformed
        double precioProducto = 22000;
        DefaultTableModel model = (DefaultTableModel) tblProducto.getModel();
        model.addRow(new Object[]{"Pizza mexicana", "1", precioProducto});
        costoProducto();
    }//GEN-LAST:event_btnMexicanaActionPerformed

    private void btnPastorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastorActionPerformed
        double precioProducto = 23000;
        DefaultTableModel model = (DefaultTableModel) tblProducto.getModel();
        model.addRow(new Object[]{"Pizza al pastor", "1", precioProducto});
        costoProducto();
    }//GEN-LAST:event_btnPastorActionPerformed

    private void btnCarbonaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarbonaraActionPerformed
        double precioProducto = 24000;
        DefaultTableModel model = (DefaultTableModel) tblProducto.getModel();
        model.addRow(new Object[]{"Pizza carbonara", "1", precioProducto});
        costoProducto();
    }//GEN-LAST:event_btnCarbonaraActionPerformed

    private void btnCasaBlancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCasaBlancaActionPerformed
        double precioProducto = 24000;
        DefaultTableModel model = (DefaultTableModel) tblProducto.getModel();
        model.addRow(new Object[]{"Pizza casa blanca", "1", precioProducto});
        costoProducto();
    }//GEN-LAST:event_btnCasaBlancaActionPerformed

    private void btnPeperoniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeperoniActionPerformed
        double precioProducto = 26500;
        DefaultTableModel model = (DefaultTableModel) tblProducto.getModel();
        model.addRow(new Object[]{"Pizza peperoni", "1", precioProducto});
        costoProducto();
    }//GEN-LAST:event_btnPeperoniActionPerformed

    private void btnTentacionEspañolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTentacionEspañolaActionPerformed
        double precioProducto = 24500;
        DefaultTableModel model = (DefaultTableModel) tblProducto.getModel();
        model.addRow(new Object[]{"Pizza tentacion española", "1", precioProducto});
        costoProducto();
    }//GEN-LAST:event_btnTentacionEspañolaActionPerformed

    private void btnRancheraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRancheraActionPerformed
        double precioProducto = 26500;
        DefaultTableModel model = (DefaultTableModel) tblProducto.getModel();
        model.addRow(new Object[]{"Pizza ranchera", "1", precioProducto});
        costoProducto();
    }//GEN-LAST:event_btnRancheraActionPerformed

    private void btnBarbacoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarbacoaActionPerformed
        double precioProducto = 27500;
        DefaultTableModel model = (DefaultTableModel) tblProducto.getModel();
        model.addRow(new Object[]{"Pizza barbacoa", "1", precioProducto});
        costoProducto();
    }//GEN-LAST:event_btnBarbacoaActionPerformed

    private void btnCuatroEstacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuatroEstacionesActionPerformed
        double precioProducto = 27500;
        DefaultTableModel model = (DefaultTableModel) tblProducto.getModel();
        model.addRow(new Object[]{"Pizza cuatro estaciones", "1", precioProducto});
        costoProducto();
    }//GEN-LAST:event_btnCuatroEstacionesActionPerformed

    private void btnCarnesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarnesActionPerformed
        double precioProducto = 27500;
        DefaultTableModel model = (DefaultTableModel) tblProducto.getModel();
        model.addRow(new Object[]{"Pizza carnes", "1", precioProducto});
        costoProducto();
    }//GEN-LAST:event_btnCarnesActionPerformed

    private void btnDiavolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiavolaActionPerformed
        double precioProducto = 28500;
        DefaultTableModel model = (DefaultTableModel) tblProducto.getModel();
        model.addRow(new Object[]{"Pizza diavola", "1", precioProducto});
        costoProducto();
    }//GEN-LAST:event_btnDiavolaActionPerformed

    private void btnPolloChampiñonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPolloChampiñonesActionPerformed
        double precioProducto = 22000;
        DefaultTableModel model = (DefaultTableModel) tblProducto.getModel();
        model.addRow(new Object[]{"Pizza pollo champiñon", "1", precioProducto});
        costoProducto();
    }//GEN-LAST:event_btnPolloChampiñonesActionPerformed

    private void btnPolloBbqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPolloBbqActionPerformed
        double precioProducto = 23000;
        DefaultTableModel model = (DefaultTableModel) tblProducto.getModel();
        model.addRow(new Object[]{"Pizza pollo BBQ", "1", precioProducto});
        costoProducto();
    }//GEN-LAST:event_btnPolloBbqActionPerformed

    private void btnPolloMielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPolloMielActionPerformed
        double precioProducto = 24000;
        DefaultTableModel model = (DefaultTableModel) tblProducto.getModel();
        model.addRow(new Object[]{"Pizza pollo miel", "1", precioProducto});
        costoProducto();
    }//GEN-LAST:event_btnPolloMielActionPerformed

    private void btnCocaColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocaColaActionPerformed
        double precioProducto = 3000;
        DefaultTableModel model = (DefaultTableModel) tblProducto.getModel();
        model.addRow(new Object[]{"Coca cola 25ml", "1", precioProducto});
        costoProducto();
    }//GEN-LAST:event_btnCocaColaActionPerformed

    private void btnMiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiloActionPerformed
        double precioProducto = 11000;
        DefaultTableModel model = (DefaultTableModel) tblProducto.getModel();
        model.addRow(new Object[]{"Milo frio", "1", precioProducto});
        costoProducto();
    }//GEN-LAST:event_btnMiloActionPerformed

    private void btnLimonadaCocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimonadaCocoActionPerformed
        double precioProducto = 11000;
        DefaultTableModel model = (DefaultTableModel) tblProducto.getModel();
        model.addRow(new Object[]{"Limonada coco", "1", precioProducto});
        costoProducto();
    }//GEN-LAST:event_btnLimonadaCocoActionPerformed

    private void txtCodigoBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoBarraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoBarraActionPerformed

    private void btnBorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTodoActionPerformed
        txtRecibido.setText("");
        txtCambio.setText("");
    }//GEN-LAST:event_btnBorrarTodoActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        if (!txtRecibido.getText().contains(".")) {
            txtRecibido.setText(txtRecibido.getText() + btnPunto.getText());
        }
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCeroActionPerformed
        String numero = txtRecibido.getText();
        if (numero == "") {
            txtRecibido.setText(btnCero.getText());
        } else {
            numero = txtRecibido.getText() + btnCero.getText();
            txtRecibido.setText(numero);
        }
    }//GEN-LAST:event_btnCeroActionPerformed

    private void btnUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnoActionPerformed
        String numero = txtRecibido.getText();
        if (numero == "") {
            txtRecibido.setText(btnUno.getText());
        } else {
            numero = txtRecibido.getText() + btnUno.getText();
            txtRecibido.setText(numero);
        }
    }//GEN-LAST:event_btnUnoActionPerformed

    private void btnDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosActionPerformed
        String numero = txtRecibido.getText();
        if (numero == "") {
            txtRecibido.setText(btnDos.getText());
        } else {
            numero = txtRecibido.getText() + btnDos.getText();
            txtRecibido.setText(numero);
        }
    }//GEN-LAST:event_btnDosActionPerformed

    private void btnTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTresActionPerformed
        String numero = txtRecibido.getText();
        if (numero == "") {
            txtRecibido.setText(btnTres.getText());
        } else {
            numero = txtRecibido.getText() + btnTres.getText();
            txtRecibido.setText(numero);
        }
    }//GEN-LAST:event_btnTresActionPerformed

    private void btnCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuatroActionPerformed
        String numero = txtRecibido.getText();
        if (numero == "") {
            txtRecibido.setText(btnCuatro.getText());
        } else {
            numero = txtRecibido.getText() + btnCuatro.getText();
            txtRecibido.setText(numero);
        }
    }//GEN-LAST:event_btnCuatroActionPerformed

    private void btnCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCincoActionPerformed
        String numero = txtRecibido.getText();
        if (numero == "") {
            txtRecibido.setText(btnCinco.getText());
        } else {
            numero = txtRecibido.getText() + btnCinco.getText();
            txtRecibido.setText(numero);
        }
    }//GEN-LAST:event_btnCincoActionPerformed

    private void btnSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeisActionPerformed
        String numero = txtRecibido.getText();
        if (numero == "") {
            txtRecibido.setText(btnSeis.getText());
        } else {
            numero = txtRecibido.getText() + btnSeis.getText();
            txtRecibido.setText(numero);
        }
    }//GEN-LAST:event_btnSeisActionPerformed

    private void btnSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSieteActionPerformed
        String numero = txtRecibido.getText();
        if (numero == "") {
            txtRecibido.setText(btnSiete.getText());
        } else {
            numero = txtRecibido.getText() + btnSiete.getText();
            txtRecibido.setText(numero);
        }
    }//GEN-LAST:event_btnSieteActionPerformed

    private void btnOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOchoActionPerformed
        String numero = txtRecibido.getText();
        if (numero == "") {
            txtRecibido.setText(btnOcho.getText());
        } else {
            numero = txtRecibido.getText() + btnOcho.getText();
            txtRecibido.setText(numero);
        }
    }//GEN-LAST:event_btnOchoActionPerformed

    private void btnNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNueveActionPerformed
        String numero = txtRecibido.getText();
        if (numero == "") {
            txtRecibido.setText(btnNueve.getText());
        } else {
            numero = txtRecibido.getText() + btnNueve.getText();
            txtRecibido.setText(numero);
        }
    }//GEN-LAST:event_btnNueveActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblProducto.getModel();
        int eliminarProducto = tblProducto.getSelectedRow();
        if (eliminarProducto >= 0) {
            model.removeRow(eliminarProducto);
        }
        costoProducto();
        if (cbxMetodoPago.getSelectedItem().equals("Efectivo")) {
            cambio();
        }
        String numero = txtRecibido.getText();
        if (numero == "" && cbxMetodoPago.equals("Efectivo")) {
            txtCambio.setText("");
            txtRecibido.setText("");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel) tblProducto.getModel();
        RecordTable.setRowCount(0);
        txtCambio.setText("");
        txtRecibido.setText("");
        txtIva.setText("");
        txtArea.setText("");
        txtSubTotal.setText("");
        txtTotal.setText("");
        txtCodigoBarra.setText("");

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        try {
            int refs = 1325 + (int) (Math.random() * 4238);

            Calendar tiempo = Calendar.getInstance();
            tiempo.getTime();
            SimpleDateFormat tTiempo = new SimpleDateFormat("HH:mm:ss");
            tTiempo.format(tiempo.getTime());
            SimpleDateFormat dia = new SimpleDateFormat("dd-MMM-YYYY");
            dia.format(tiempo.getTime());
            txtArea.append(
                    "Casa Blanca\n"
                    + "Pizzeria-Heladeria\n"
                    + "Cra 9 #29-28\n"
                    + "Sogamoso-Boyaca\n"
                    + "Nit:2828210218-9\n"
                    + "Regimen simplificado\n"
                    + "Factura No: " + refs + "\n"
                    + "====================" + "\n\n"
                    + "SubTotal: " + txtSubTotal.getText() + "\n"
                    + "Iva: " + txtIva.getText() + "\n"
                    + "Total: " + txtTotal.getText() + "\n"
                    + "Recibido: " + "$" + txtRecibido.getText() + "\n"
                    + "Cambio: " + txtCambio.getText() + "\n"
                    + "===================="
                    + "\nFecha: " + dia.format(tiempo.getTime())
                    + "\nHora: " + tTiempo.format(tiempo.getTime())
                    + "\n*Gracias por su compra*\n"
            );
            MessageFormat header=new MessageFormat("Impresion en progreso");
            MessageFormat footer=new MessageFormat("Page {0,number,integer}");
            txtArea.print();

        } catch (PrinterException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBarbacoa;
    private javax.swing.JButton btnBorrarTodo;
    private javax.swing.JButton btnCarbonara;
    private javax.swing.JButton btnCarnes;
    private javax.swing.JButton btnCasaBlanca;
    private javax.swing.JButton btnCero;
    private javax.swing.JButton btnCinco;
    private javax.swing.JButton btnCocaCola;
    private javax.swing.JButton btnCuatro;
    private javax.swing.JButton btnCuatroEstaciones;
    private javax.swing.JButton btnDiavola;
    private javax.swing.JButton btnDos;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnExplosionTocineta;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnLimonadaCoco;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMail;
    private javax.swing.JButton btnMexicana;
    private javax.swing.JButton btnMilo;
    private javax.swing.JButton btnNueve;
    private javax.swing.JButton btnOcho;
    private javax.swing.JButton btnPago;
    private javax.swing.JButton btnPastor;
    private javax.swing.JButton btnPeperoni;
    private javax.swing.JButton btnPolloBbq;
    private javax.swing.JButton btnPolloChampiñones;
    private javax.swing.JButton btnPolloMiel;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnRanchera;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSeis;
    private javax.swing.JButton btnSiete;
    private javax.swing.JButton btnTentacionEspañola;
    private javax.swing.JButton btnTres;
    private javax.swing.JButton btnUno;
    private javax.swing.JComboBox<String> cbxMetodoPago;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblProducto;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtCambio;
    private javax.swing.JTextField txtCodigoBarra;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtRecibido;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
